version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: educlove-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - educlove-network

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: educlove-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
    depends_on:
      - mongo
    networks:
      - educlove-network

volumes:
  mongo-data:

networks:
  educlove-network:
    driver: bridge
